name: Docker Image CI

on: 
  push: {}
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        runs: printenv | sort
      -
        uses: actions/checkout@v2
      -
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Tree buildx-cache 1
        run: |
          sudo apt-get install tree
          mkdir -p /tmp/.buildx-cache
          cd /tmp/.buildx-cache
          tree -f --du
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=false" \
            --tag ${{ github.repository }} \
            --file ./Dockerfile \
            ${{ github.workspace }}
      -
        name: Tree buildx-cache 2
        run: |
          cd /tmp/.buildx-cache
          tree -f --du

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Tree buildx-cache 1
        run: |
          sudo apt-get install tree
          mkdir -p /tmp/.buildx-cache
          cd /tmp/.buildx-cache
          tree -f --du
      -
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Tree buildx-cache 2
        run: |
          cd /tmp/.buildx-cache
          tree -f --du
      -
         name: Docker Buildx (cached)
         run: |
           docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --output "type=image,push=false" \
            --tag ${{ github.repository }} \
            --file ./Dockerfile \
            ${{ github.workspace }}
      -
        name: Tree buildx-cache 3
        run: |
          cd /tmp/.buildx-cache
          tree -f --du
